#define MAX_WORD_LENGTH 12
#define WORD_COUNT 9
const char words[WORD_COUNT][MAX_WORD_LENGTH] PROGMEM = {
  "OXO",
  "OXOX",
  "OXOXO",
  "OXOXOX",
  "OXOXOXO",
  "OXOXOXOX",
  "OXOXOXOXO",
  "OXOXOXOXOX",
  "OXOXOXOXOXO",
};